---
- name: install metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: curl metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: dpkg metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: copy config file to hosts
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable metricbeat module
    command: metricbeat modules enable docker

  - name: metricbeat setup
    command: metricbeat setup

  - name: metricbeat -e
    command: service metricbeat start -e

  - name: enable on boot
    systemd:
      name: metricbeat
      enabled: yes
